#!/bin/sh
mkdir -p /tmp/rpmbuild/SOURCES
mv sources/* /tmp/rpmbuild/SOURCES
yum-builddep -y *.spec
rpmbuild -ba --define="_topdir /tmp/rpmbuild" *.spec
ret=$?
mv $(find /tmp/rpmbuild -name \*.rpm) .
exit $ret
