#!/bin/sh
# Record the /etc/os-release ID, so we can tell opensuse-leap from sles
. /etc/os-release
echo "%os_release_id $ID" > /etc/rpm/os-release-id

if [ $ID = 'opensuse-leap' ] || [ $ID = 'sles' ]; then
    INSTALL='zypper --non-interactive install'
fi

mkdir -p /tmp/rpmbuild/SOURCES
mv sources/* /tmp/rpmbuild/SOURCES

# Install the build dependencies
if [ $ID = 'almalinux' ] || [ $ID = 'amzn' ] || [ $ID = 'fedora' ]; then
    yum-builddep -y *.spec
fi

# Install the build dependencies
if [ $ID = 'opensuse-leap' ] || [ $ID = 'sles' ]; then
    # shellcheck disable=SC2046 # we want word splitting
    $INSTALL $(rpmspec --parse *.spec | grep '^BuildRequires:' | sed -e 's/^BuildRequires://' | sed -e 's/,/ /')
fi

rpmbuild -ba --define="_topdir /tmp/rpmbuild" *.spec
ret=$?
mv $(find /tmp/rpmbuild -name \*.rpm) .
rpmlint *.rpm
exit $ret
